### ISSUE TITLE
Allow opening HTML files on SD card

### ISSUE THREAD

**Issue by JonasCz** [anthonycr/Lightning-Browser#170] opened 2015-01-30 13:20 UTC
I would like to be able to open HTML files stored on SD card. 
If I enter 'file:///sdcard/myhtmlfile.html in URL box, it gives a toast 'Local file blocked from loading'
Maybe you could fix this?

**Comment by kuc** [comment] 2015-01-30 13:38
This can't be fixed on non-rooted devices. And if you your device is rooted, you can fix this yourself:
http://technofaq.org/posts/2014/04/fixing-external-sd-card-write-issue-on-android-kitkat/

**Comment by JonasCz** [comment] 2015-01-31 16:22
No, this does not only happen on KitKat. Other browsers (stock, Firefox,
WebView in my own app ) on my 4.2 phone can open files. I believe the
WebView can  be set to load local files by:
myWebView.getSettings().setAllowFileAccess(true) or similar.
On Jan 30, 2015 1:38 PM, "Miłosz" <notifications@github.com> wrote:

This can't be fixed on non-rooted devices. And if you your device is
rooted, you can fix this yourself:
http://technofaq.org/posts/2014/04/fixing-external-sd-card-write-issue-on-android-kitkat/

—
Reply to this email directly or view it on GitHub
<https://github.com/anthonycr/Lightning-Browser/issues/170#issuecomment-72201392>
.

**Comment by anthonycr** [comment] 2015-02-01 04:04
@JonasCz that setting is already enabled, the issue is that I was blocking loading of local html files unless I explicitly loaded it (like homepage or history) because it posed a security threat. In reality the security threat was from Intents and other apps opening file urls in Lightning, so I've removed the block on entering file urls into the search bar but have kept the block on Intents opening file urls for security reasons. It actually should be live in the latest beta. 

Please comment back if it's not working as you in the latest beta, and I'll reopen the issue, otherwise I'll assume it's fixed for you (I just tried it on my device and it worked after the change I made the other day). :-)

**Closed by anthonycr** 2015-02-01 04:04 UTC

**Comment by JonasCz** [comment] 2015-02-03 13:03
Thanks, works great now !
