### ISSUE TITLE
Not display new pages button?

### ISSUE THREAD

**Issue by AlphaOmega3** [anthonycr/Lightning-Browser#475] opened 2016-10-02 02:55 UTC
Hi. When I have to open many pages in succession it gets annoying having to always go back to that base (given that automatically displays the new open). it would be possible to add, in the settings, the button "does not move to the new just open windows"?

**Comment by kuc** [comment] 2016-10-02 09:06
Duplicate of #399, #318
PR waiting: #356

**Closed** 2016-10-02 10:02 UTC
