### ISSUE TITLE
fc

### ISSUE THREAD

**Issue by ali-libre** [anthonycr/Lightning-Browser#216] opened 2015-04-29 01:32 UTC
New version dont start...just force close.
Clean data no reaolved yet.

**Comment by aelmahmoudy** [comment] 2015-04-29 12:09
Duplicate of #213

**Comment by ali-libre** [comment] 2015-04-29 13:32
I have lastest version think...4.0.8a

**Comment by deavmi** [comment] 2015-05-01 11:41
Also having this problem.

I am on Android Lollipop.

**Comment by ali-libre** [comment] 2015-05-01 12:08
Only last version have this problem 4.0.8a.
Android 4.3.1

**Comment by ali-libre** [comment] 2015-05-01 12:25
4.0.9 got fc too.
But 4.0.2 work

**Comment by anthonycr** [comment] 2015-05-01 12:52
This is a problem in the build for F-droid. There's one of two possibilities based on the other force close bug that's open: 
1. The F-droid build didn't update to the latest App-compat support library
2. Updating to the latest version of libnetcipher (which broke the travis build) is breaking the build.

This will all be resolved when I switch to Android Studio, but for what it's worth, the Play Store version of the app doesn't have this FC. I'm not sure who makes the build for F-droid so I'm not sure who to needs to be contacted to get it fixed.

**Comment by deavmi** [comment] 2015-05-01 13:01
@anthonycr 

If F-Droid clones the source code, the new libraries should come with right.

Therefore maybe it is number `2`.

**Comment by anthonycr** [comment] 2015-05-01 13:37
@deavmi yes, but the libraries aren't included in the source code, only the references too the external libraries, so it is up to the discretion of the developer to choose which versions of those libraries to use (see project.properties, it only references appcompat and palette but not the versions), so it is possible to compile with the wrong library. When I switch to gradle then it will specify the correct version and this won't be a problem because the version won't be ambiguous. The problem we have is that there was a major update to the appcompat library and the browser switched to using that version, but an automatic build wouldn't catch it using Ant an the way the build is set up.

**Comment by deavmi** [comment] 2015-05-01 13:39
@anthonycr How does it now where to find the library, does it fetch it over the net from an external source and then include it in the code and start compiling?

**Closed** 2015-08-21 01:10 UTC
