### ISSUE TITLE
Incognito mode : delete cookies ?

### ISSUE THREAD

**Issue by David-Guillot** [anthonycr/Lightning-Browser#248] opened 2015-05-24 15:15 UTC
Hello,

Currently when cookies are enabled in incognito mode, they are not deleted when closing the application, making this mode not that incognito... For example I use incognito mode to log into my Google account, then I close my browser ans I use incognito mode for something else : Google knows it because I'm still authentified on their side... I would vote for forcing incognito cookies deletion when closing the browser, but a checkbox would be okay too ;-) 

Thanks !

**Comment by anthonycr** [comment] 2015-05-26 11:35
Cookies are actually disabled when in incognito, so if they are not on your device, it's a bug. There is a setting to force incognito cookies on (advanced settings), but that is default disabled. Check if that checkbox is checked. The way cookies work, incognito cookies and normal cookies are shared and I can't stop that from happening, so the most secure way is to completely disable cookies.

Let me know if you have that setting on, causing this problem.

**Comment by David-Guillot** [comment] 2015-05-26 12:56
Yes I have this setting on because I want to be able to have sessions on some websites while in incognito mode (to check my Google account for example because I don't want Google to see what I'm doing in my "normal" tabs). I thought incognito cookies would be destroyed when closing the browser...

So you said incognito cookies and normal cookies are shared ? Does this mean that third-party cookies for example, say cookies that are set by an ad-server while I'm browsing incognito with cookies, can be used by the same ad-server in normal tabs ?

**Comment by rigid** [comment] 2015-06-08 21:06
kind of duplicate of #245
I'm sad to hear that @anthonycr , browsing without cookies is strongly limited nowadays which renders "incognito mode" almost useless.
As a workaround, one could use 2 different browser apps. But who wants to use another browser than lightning ;)

**Closed** 2019-08-05 21:39 UTC
